[package]
name = "scotch-sys"
version = "0.1.0"
authors = ["Hubert Hirtz <hubert@hirtz.pm>"]
edition = "2018"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = { version = "0.58", default-features = false, features = ["runtime", "which-rustfmt"] }
